### ISSUE TITLE
Create SHU token contract on Optimism

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/shutter-bridge-op#1]
<h2>Create SHU token on OP</h2>
<p><a href="https://docs.optimism.io/builders/app-developers/tutorials/standard-bridge-standard-token">Following this tutorial on OP Docs</a> → <strong>Creating your Bridged Asset on L2</strong></p>
<ol>
<li>Create a repo for working on the bridge.
<ol>
<li>Using hardhat since no smart contract development will be made.
<ol>
<li><a href="https://github.com/blockful-io/shutter-bridge-op">https://github.com/blockful-io/shutter-bridge-op</a></li>
</ol>
</li>
</ol>
</li>
<li>Create a Testnet $SHU token
<ol>
<li>Create a Token contract.</li>
<li>Deploy on Sepolia</li>
<li>Verify contract</li>
<li>Mint tokens to deployer</li>
</ol>
</li>
<li>Create the L2 $SHU token using <a href="https://sepolia-optimism.etherscan.io/address/0x4200000000000000000000000000000000000012">OptimismMintableERC20Factory</a>
<ol>
<li>Note that it's impossible to verify on OP Sepolia because they don't have an API for Sepolia (yes, they don't). But on the mainnet, similar deploys will recognize the bytecode and be verified by default.</li>
</ol>
</li>
</ol>
<p><a href="https://docs.optimism.io/builders/app-developers/tutorials/cross-dom-bridge-erc20">Deposit Tutorial on OP Docs</a> → <strong>Bridging ERC-20 Tokens to OP Mainnet</strong></p>
<p>Beforehand, the SDK is strictly made for EOA, assuming that most bridge transactions will originate via governance (not EOA), the bridge methods are preferred using straightforward ethers.</p>
<ol>
<li>Approve L1StandardBridge to spend $SHU
<ol>
<li>Connect to $SHU</li>
<li>Set amount to bridge</li>
<li>Call approve</li>
</ol>
</li>
<li>Bridge using L1StandardBridge
<ol>
<li>Connect to L1StandardBridge</li>
<li>Call <code>bridgeERC20to</code>
<ol>
<li>localToken → The $SHU token address on mainnet</li>
<li>remoteToken → The $SHU bridged version that we deployed early</li>
<li>receiver → The receiver address</li>
<li>amount → The amount to be received</li>
<li>gasLimit → This variable is kinda unclear, most users are using 200_000 for L1→L2 but the SDK places 0 and sometime around 288_000. Based on patterns I recommend 200_000 for L1→L2 and 300_000 for L2→L1</li>
<li>extraData → Extra data, made for recognizing transactions and elaborating other mechanics. Should be set to “0x” in our case</li>
</ol>
</li>
</ol>
</li>
</ol>
<p><a href="https://docs.optimism.io/builders/app-developers/tutorials/cross-dom-bridge-erc20">Withdraw Tutorial on OP Docs</a> → <strong>Bridging ERC-20 Tokens to ETH Mainnet With the Optimism SDK</strong></p>
<p>Now the complex part of Optimism is the way back to Ethereum. We've seen that OP has one of the greatest validation times when withdrawing ETH from OP via exchanges. But for the Portal Bridge that is on a whole new level. It takes 7 days of validation from the Fault Proof mini-game. This means that after you withdraw, you must wait 7 days to guarantee there were no disputes.</p>
<p>Withdraw the tokens from Optimism and prove the withdrawal on L1:</p>
<ol>
<li>
<p>Bridge using the L2StandardBridge</p>
<ol>
<li>
<p>Connect to the L2StandardBridge</p>
</li>
<li>
<p>Call <code>bridgeERC20to</code></p>
<p>It's the same parameters as the L1→L2 expect that the <code>localToken</code> and <code>remoteToken</code> will be flipped:</p>
<ol>
<li>localToken → The $SHU bridged token</li>
<li>remoteToken → The $SHU token address on mainnet</li>
<li>gasLimit → 300_000</li>
</ol>
</li>
<li>
<p>Get the Transaction Hash of this withdraw operation</p>
</li>
</ol>
</li>
<li>
<p>Prove the withdraw</p>
<p>This next step is obliged to use the OP SDK because of the proofs it needs to generate based on the withdrawal operation. You can check the transaction arguments below:</p>
<details>
  <summary><h4>e.g.: proveWithdrawalTransaction(…) input args</h4></summary>
<p>Function: proveWithdrawalTransaction((uint256,address,address,uint256,uint256,bytes), uint256, (bytes32,bytes32,bytes32,bytes32), bytes[])</p>

| # | Name | Type | Data |
-- | -- | -- | --
| 0 | _tx.nonce | uint256 | 1766847064778384329583297500742918515827483896875618958121606201292623937 |
| 0 | _tx.sender | address | https://sepolia.etherscan.io/address/0x4200000000000000000000000000000000000007 |
| 0 | _tx.target | address | https://sepolia.etherscan.io/address/0x58Cc85b8D04EA49cC6DBd3CbFFd00B4B8D6cb3ef |
| 0 | _tx.value | uint256 | 0 |
| 0 | _tx.gasLimit | uint256 | 491822 |
| 0 | _tx.data | bytes | 0xd764ad0b0001000000000000000000000000000000000000000000000000000000000fa70000000000000000000000004200000000000000000000000000000000000010000000000000000000000000fbb0621e0b23b5478b630bd55a5f21f67730b0f100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030d4000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000e40166a07a00000000000000000000000094b713781143b8eb3c9e334c1523f067990c90b3000000000000000000000000428225a7b4d4ab16f5548f6a4aafffd80e419e74000000000000000000000000935a5f21d7f5113c7888f4083536fbafa430d144000000000000000000000000935a5f21d7f5113c7888f4083536fbafa430d1440000000000000000000000000000000000000000000000000de0b6b3a764000000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 |
| 2 | _disputeGameIndex | uint256 | 12442 |
| 2 | _outputRootProof.version | bytes32 | 0x0000000000000000000000000000000000000000000000000000000000000000 |
| 2 | _outputRootProof.stateRoot | bytes32 | 0x58df63da02fe8710731e8339faacf3cf6854af96065d8e4c538d4538b4be62d4 |
| 2 | _outputRootProof.messagePasserStorageRoot | bytes32 | 0x2b2fce9e158ea78b90e3d4e669f568212ac8c82b72fb664d9c9d096d6cc7e35b |
| 2 | _outputRootProof.latestBlockhash | bytes32 | 0xb7db2b69911b5b04e1ba9c034436c66d99a3442e482206828931026f5a51535a |
| 3 | _withdrawalProof | bytes | 0xf90211a0beba5fa78e61cfb87fc0f47ff3ad5575ff010724002278a62afca80f9d14d6b9a06cf6d0a1803eeeaef5a665e955bdd349e4680917bf984d286c47ff70b645f676a0c6a9d5211e41e69fa5b68de496bb653327d75613b749f734ba125e711b638133a02374a089b4ca375563c5b3d50fb3fd3852bbc9ae51fa76a8768f981d52504650a0a409a601d3c5e44fafacd49d84baad721c5815256d3d0b673c7932668a690b3da0c3b320796e689fd19b7a63843ccc9465165db141206ce5a13f1afb0a53e5a9d7a086eef27429abd2c41c48b9ba80a52cfbc78d581c524d2d00ec79cf6aa23aae51a06746a7e4a8ef65a30e7cb3221e0e5b88ae96c82884070bd8d785f47c72039b1ba03b47236f2f99788471c8620485529fd5b5b367b02429cc4dfc5a8942354f0487a094179e4cfb4e00690015df19158a5a7aa5a5ee93d773512915c965c67638ea6aa0a08ddff3f2204ddb6bd30d7066d0dd7535f253dbb190d62322699f774b1e6bf5a0e3e9b78b19287684acefb3d8dec5496c4c92309af594e90b1245bf388dd50e40a070de0e8c3abae7290d19712f25c1e55bb162135fa10d797478142bfb80d561fda06ec12889c7684f1178acbb95991af2fb4749410931fdc0c1ebd6475902f41789a0d9e9168332a549a3bbe014d81b2e81abd70158c8c542153fa7cbee0978b30ae8a0d7b79bf2bf30427220d52ee991469d1119b834b2c679ee7e40250aaf1b322f5e80 |
| 4 | _withdrawalProof | bytes | 0xf90211a098099f15a5aa0b529777432f45c99acc2d95aa94222f8b33cde1831fc28103cba037537f1b12e1efb6fc4d5c91a07e7da27a93867077cd77db854bee853ec06479a042b5b53390acf9e3de83ca345c66b3ea6e5e37d7705f30b5086e960f571e326aa00527236f2b7392acfe6253f3b0de48c6e9a28b42d133418559571fde65e2af10a0c204bc0005f209ca378ff6180f099d11702afeabf8816b68f4d76c8295607828a03e6e9f049bd9ce6a2bc05698e4370fc11a42557b93127c517ae3d0b97a5492f1a07a820425a5b01b3308593f86edcf7d86738c9a4f0174f813084ffe698dfb0b0ca0a7b1a8d8a235d1326bdd010ba33ad3d75204152d9d5e61643bd7111ef523c24ea06a04f4a74ded79c04a4677b32d45f21a09a1b5c6aefca0005639d7c50773ec80a04842f66c2a86d4a7795910b8b1414d7a73bb8ac223e4a8333f129dfc46b19b65a034d3bcf2fdd52430250432bf925986075fce4be1912368b822c515fde78dd200a0d0e1f24e807ec7865820a0c8dd79db80d8816606c79c982ef0a4f4eddec03501a080ebf72f9df2b5981617d6dbff315ad53f4f328cd3a49f8aa65b2667bbbb0e7ba0054e375049ab7494ee575436e4ed605bcdb7f0361668f93ebb58e073459f78f6a023e53ecd253857764c10eaa0db6d51d8c4f85348278777f51ded4f2c9609629ca01dc9e6930831292b08b6a6d49aa57a7bf717869c3a7d6fc35d3a8980e1bd897e80 |
| 5 | _withdrawalProof | bytes | 0xf901518080a0a69273d3b3a6976cff717641d89e5a1054c11422d84242733c66988060f2765ca00da2b703dbffde3cc11b2979c53e23af65bd1aea457ea5f31b95c763cd3c97138080a00ac01dd73806d50d812ffe227ad0093adcfee9b509d13df1db438535a1a41f68a0293fbf34d7cf2da5350fdd4fda76b456c6b101539a0bb6f4c070619b44c430e3a0710751be5ad0663d5508483755caa04fa21d7554cc3ed0e7e18a18b8d72da2ee80a0819925131728e648d1ed7f002b33a1da682c4a32a1f7c12f06b8519b3c4de9e3a0551ee455c5d565f16b12fc67f47d3ca5c6fb32b03b87304c1b6659fd7e130a9a80a0b4205abfbc67bfc0d73bebc525c6f56877c11bb81c19407840cb64b95a2edfb5a0e8146ee9d70ef11e81d255bc9daca27d5eb12ba5d3cc09973be3f6aaf7592191a0596cc1961286aa68f1f05a2dca5328da9f7c37ffcccadb679ebe99bff661e1c880 |
| 6 | _withdrawalProof | bytes | 0xf8518080a046c62265c6c27edbbb16e2da0e284b3f3246fcfa6b4b4dd4035e2db2efb507908080808080808080808080a0ab3745fc3e78601812c8eebd5fd9082d2fcffd2734952f2b31ebf761d160576a8080 |
| 7 | _withdrawalProof | bytes | 0xe19f202645b6384c95bba268ec64784ba40d0e17ec6155e3a4cee93b4c43b3678501 |

</details>

<p>To prove a withdrawal you don't need to be the owner of the Tx in the matter. Anyone can prove any transaction hash. This process will cost gas and a total of 2 transactions are needed in two different time frames:</p>
<ol>
<li>Place the withdraw hash on the <code>proveWithdraw</code> script and run it</li>
<li>Wait for the withdrawal request’s block to be validated on Ethereum (this can take a few minutes)</li>
<li>Prove the transaction by calling <code>proveWithdrawalTransaction</code></li>
<li>Wait for 7 days for the Fault tolerance</li>
<li>Finalize the transaction by calling <code>finalizeWithdrawalTransactionExternalProof</code></li>
</ol>
<p>You can simply run the <code>proveWithdraw</code> script that Blockful prepared and the SDK will smoothly try each step until they are all concluded.</p>
</li>
</ol>

Resources:
- [OP Bridge docs](https://docs.optimism.io/builders/app-developers/bridging/standard-bridge#bridged-tokens)
- [OP SDK docs](https://docs.optimism.io/builders/app-developers/tutorials/cross-dom-bridge-erc20)
- [Forum post](https://shutternetwork.discourse.group/t/proposal-to-deploy-a-dex-pool-on-a-low-cost-chain-part-3/370)

**Comment by 0xneves** [comment]
I will update this issue tomorrow cause today I had a major challenge with the OP team (still ongoing), in short words:
- The L2 to L1 bridge cannot be easily made from a contract perspective, only with EOA using the OP SDK

This means that in theory, we will need a lot of time and effort to allow a multi-sig to burn SHU on L2 and unlock on L1. Relaying to a team maybe be an easier path. I will sync with the team tomorrow and try to ping some contacts on OP that might be able to help.

**Comment by alextnetto** [comment]
@0xneves  Test withdraw on mainnet this friday (16th Aug)
